### ISSUE TITLE
 Efficient Deep Embedded Subspace Clustering

### ISSUE THREAD

**Issue by cquzys** [JinyuCai95/JinyuCai95.github.io#1]
Hi author:
   Can you share the codes of  Efficient Deep Embedded Subspace Clustering?

Thanks

**Comment by JinyuCai95** [comment]
你好，我已收到你的邮件(*^__^*)

**Comment by JinyuCai95** [comment]
Hi,
    Thanks for your attention to our work, the code now can be found in my repositories.
Best regards.
